// Mocks generated by Mockito from annotations
// in ditonton/test/presentation/pages/home_tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:ditonton/common/state_enum.dart' as _i7;
import 'package:ditonton/domain/entities/tv_series.dart' as _i6;
import 'package:ditonton/domain/usecases/get_on_air_tv_series.dart' as _i2;
import 'package:ditonton/domain/usecases/get_popular_tv_series.dart' as _i3;
import 'package:ditonton/domain/usecases/get_top_rated_tv_series.dart' as _i4;
import 'package:ditonton/presentation/provider/tv_series_list_notifier.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetOnAirTVSeries_0 extends _i1.SmartFake
    implements _i2.GetOnAirTVSeries {
  _FakeGetOnAirTVSeries_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTVSeries_1 extends _i1.SmartFake
    implements _i3.GetPopularTVSeries {
  _FakeGetPopularTVSeries_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTVSeries_2 extends _i1.SmartFake
    implements _i4.GetTopRatedTVSeries {
  _FakeGetTopRatedTVSeries_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesListNotifier extends _i1.Mock
    implements _i5.TVSeriesListNotifier {
  MockTVSeriesListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.TVSeries> get onAirTVSeries => (super.noSuchMethod(
    Invocation.getter(#onAirTVSeries),
    returnValue: <_i6.TVSeries>[],
  ) as List<_i6.TVSeries>);

  @override
  _i7.RequestState get onAirState => (super.noSuchMethod(
    Invocation.getter(#onAirState),
    returnValue: _i7.RequestState.Empty,
  ) as _i7.RequestState);

  @override
  List<_i6.TVSeries> get popularTVSeries => (super.noSuchMethod(
    Invocation.getter(#popularTVSeries),
    returnValue: <_i6.TVSeries>[],
  ) as List<_i6.TVSeries>);

  @override
  _i7.RequestState get popularTVSeriesState => (super.noSuchMethod(
    Invocation.getter(#popularTVSeriesState),
    returnValue: _i7.RequestState.Empty,
  ) as _i7.RequestState);

  @override
  List<_i6.TVSeries> get topRatedTVSeries => (super.noSuchMethod(
    Invocation.getter(#topRatedTVSeries),
    returnValue: <_i6.TVSeries>[],
  ) as List<_i6.TVSeries>);

  @override
  _i7.RequestState get topRatedTVSeriesState => (super.noSuchMethod(
    Invocation.getter(#topRatedTVSeriesState),
    returnValue: _i7.RequestState.Empty,
  ) as _i7.RequestState);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i8.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  _i2.GetOnAirTVSeries get getOnAirTVSeries => (super.noSuchMethod(
    Invocation.getter(#getOnAirTVSeries),
    returnValue: _FakeGetOnAirTVSeries_0(
      this,
      Invocation.getter(#getOnAirTVSeries),
    ),
  ) as _i2.GetOnAirTVSeries);

  @override
  _i3.GetPopularTVSeries get getPopularTVSeries => (super.noSuchMethod(
    Invocation.getter(#getPopularTVSeries),
    returnValue: _FakeGetPopularTVSeries_1(
      this,
      Invocation.getter(#getPopularTVSeries),
    ),
  ) as _i3.GetPopularTVSeries);

  @override
  _i4.GetTopRatedTVSeries get getTopRatedTVSeries => (super.noSuchMethod(
    Invocation.getter(#getTopRatedTVSeries),
    returnValue: _FakeGetTopRatedTVSeries_2(
      this,
      Invocation.getter(#getTopRatedTVSeries),
    ),
  ) as _i4.GetTopRatedTVSeries);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> fetchOnAirTVSeries() => (super.noSuchMethod(
    Invocation.method(#fetchOnAirTVSeries, []),
    returnValue: _i9.Future<void>.value(),
    returnValueForMissingStub: _i9.Future<void>.value(),
  ) as _i9.Future<void>);

  @override
  _i9.Future<void> fetchPopularTVSeries() => (super.noSuchMethod(
    Invocation.method(#fetchPopularTVSeries, []),
    returnValue: _i9.Future<void>.value(),
    returnValueForMissingStub: _i9.Future<void>.value(),
  ) as _i9.Future<void>);

  @override
  _i9.Future<void> fetchTopRatedTVSeries() => (super.noSuchMethod(
    Invocation.method(#fetchTopRatedTVSeries, []),
    returnValue: _i9.Future<void>.value(),
    returnValueForMissingStub: _i9.Future<void>.value(),
  ) as _i9.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
